/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package fr.isep.api.controller;

import fr.isep.api.model.Error;
import fr.isep.api.model.Profile;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Api(value = "me", description = "the me API")
public interface MeApi {

    public interface AdditionInterface extends Remote {

    }
    public Addition{} throws RemoteException {

    }
    public int add(int a, int b) throws RemoteException {
        int result= a+b;
        return result;
    }

}
